### ISSUE TITLE
Combine scopes and authorization_details when authorizing issuance request

### ISSUE THREAD

**Issue by vafeini** [eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt#156]
In current implementation of the library authorization of an issuance request is based on the existence of a `scope` attribute of a credential configuration in issuer's metadata. In case the attribute is missing authorization requests do not include these credentials. 

This behavior should be changed as follows:
- In case credential configuration includes a `scope` attribute for the credential use it.
- In case credential configuration does not include a `scope` attribute create the respective authorization_detail element and include it in the authorization request.

Thus the resulting authorization requests can include both scopes and authorization details attibutes.

- [x] #147

**Comment by babisRoutis** [comment]
There are two cases for assembling an `authorization_details`:

1. Use `format` and some format-specific details (like `vct` for SD-JWT-VC) or
2. Use just a `credential_configuration_id`


Some of the VCI authors [claim](https://github.com/openid/OpenID4VCI/issues/275#issuecomment-1956168993) share opinion that VCI should remove the (1) option. Others though disagree, suggesting that (1) could be used in cases where issuer doesn't advertise in its metadata a credential.

IMO, we should drop support for the first case.  Reason is that since the introduction of `credential_configuration_id` there is a single and easy way (format agnostic) of assembling such an `authorization_details`.
